---
- name: Setup and deploy Spring Boot project
  hosts: all
  vars:
    project_repo: "https://github.com/javajack/spring-boot-jar-war-demo.git"
    project_dir: "/opt/spring-boot-demo"
    deploy_dir: "/var/www/spring-boot-demo"
    java_home: "/usr/lib/jvm/java-11-openjdk-amd64"
    build_command: "./mvnw clean package"
    app_jar: "target/spring-boot-jar-war-demo-0.0.1-SNAPSHOT.jar"
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-11-jdk
        - maven
        - git
      become: true

- name: Prepare Build Node
  hosts: build_node
  tasks:
    - name: Clone the project repository
      ansible.builtin.git:
        repo: "{{ project_repo }}"
        dest: "{{ project_dir }}"
        update: yes

    - name: Build the project
      ansible.builtin.command:
        cmd: "{{ build_command }}"
        chdir: "{{ project_dir }}"

    - name: Archive the JAR file
      ansible.builtin.archive:
        path: "{{ project_dir }}/{{ app_jar }}"
        dest: "/tmp/spring-boot-demo.jar"
        format: gz

    - name: Copy build artifact to local
      ansible.builtin.fetch:
        src: "/tmp/spring-boot-demo.jar"
        dest: /tmp/spring-boot-demo.jar
        flat: yes

- name: Deploy to Prod Node
  hosts: prod_node
  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data
      become: true

    - name: Copy build artifact to prod node
      ansible.builtin.copy:
        src: /tmp/spring-boot-demo.jar
        dest: "{{ deploy_dir }}/spring-boot-demo.jar"

    - name: Create a systemd service file for Spring Boot
      ansible.builtin.template:
        src: templates/spring-boot.service.j2
        dest: /etc/systemd/system/spring-boot-demo.service
        mode: '0644'
        owner: root
        group: root
      become: true

    - name: Reload systemd daemon
      ansible.builtin.command:
        cmd: systemctl daemon-reload
      become: true

    - name: Start Spring Boot application
      ansible.builtin.service:
        name: spring-boot-demo
        state: restarted
      become: true
